In [1]:
#pip install numpy

In [2]:
import numpy as np

In [3]:
np_array = np.array([1, 2, 3, 4, 5])

In [4]:
len(np_array)

5

In [5]:
np_array.size

5

In [6]:
np_array.shape

(5,)

In [7]:
np_array = np_array * 5
np_array

array([ 5, 10, 15, 20, 25])

In [8]:
np_array[0]

5

In [9]:
np_array[-1]

25

In [10]:
np_array[0:3]

array([ 5, 10, 15])

In [11]:
print(np_array[:2])
print(np_array[2:])

[ 5 10]
[15 20 25]


In [12]:
np_array[np_array > 10]

array([15, 20, 25])

In [13]:
print(max(np_array))
print(min(np_array))
print(np_array.min())
print(np_array.max())
print(np_array.mean())

25
5
5
25
15.0


In [14]:
players_list = [(72, 150), (70, 140), (79, 160)]
np_players = np.array(players_list)
np_players

array([[ 72, 150],
       [ 70, 140],
       [ 79, 160]])

In [15]:
np_players.shape

(3, 2)

In [16]:
np_players_updated = np_players * [0.0254, 0.455]
np_players_updated

array([[ 1.8288, 68.25  ],
       [ 1.778 , 63.7   ],
       [ 2.0066, 72.8   ]])

In [17]:
print(np_players[0]) # 1st row
print()
print(np_players[0, 0]) # 1st row, 1st column
print()
print(np_players[:, 0]) # column 1
print()
print(np_players[0, :]) # row 1

[ 72 150]

72

[72 70 79]

[ 72 150]


In [18]:
np_skills = np.array(['batsman','bowler','all-rounder'])

print(np_players[np_skills == 'batsman']) #conditional fetching

[[ 72 150]]


In [19]:
#creating 1D arrays
print('ones')
arr1 = np.ones(5, dtype = 'int')
print(arr1)
print()
print('zeros')
arr1 = np.zeros(5, dtype = 'int')
print(arr1)
print()
print('random rand')
arr1 = np.random.rand(5)
print(arr1)
print()
print('random randint')
arr1 = np.random.randint(2, 5, 5) #(uperbound, lowerbound, size)
print(arr1)
print()
print('full')
arr1 = np.full(5, 4)
print(arr1)
print()
print('linspace')
arr1 = np.linspace(5, 10, 5)
print(arr1)
print()
print('arange')
arr1 = np.arange(5)
print(arr1)

ones
[1 1 1 1 1]

zeros
[0 0 0 0 0]

random rand
[0.28874915 0.49935673 0.42603446 0.5892428  0.58007854]

random randint
[4 3 4 2 3]

full
[4 4 4 4 4]

linspace
[ 5.    6.25  7.5   8.75 10.  ]

arange
[0 1 2 3 4]


In [20]:
#creating 2D arrays
print('ones')
arr1 = np.ones((3,5), dtype = 'int')
print(arr1)
print()
print('zeros')
arr1 = np.zeros((3,5), dtype = 'int')
print(arr1)
print()
print('random rand')
arr1 = np.random.rand(3,5)
print(arr1)
print()
print('random randint')
arr1 = np.random.randint(2, 5, (3,5)) #(uperbound, lowerbound, size)
print(arr1)
print()
print('full')
arr1 = np.full((3,5), 4)
print(arr1)
print()
print('linspace')
arr1 = np.linspace(5, 10, 12)
# Reshape it into a 2D array with 3 rows and 4 columns
arr1 = arr1.reshape(3, 4)
print(arr1)
print()
print('arange')
arr1 = np.arange(12)
# Reshape it into a 2D array with 3 rows and 4 columns
arr1 = arr1.reshape(3, 4)
print(arr1)
print()

ones
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

zeros
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

random rand
[[0.38634028 0.10540751 0.2404324  0.07887904 0.54087684]
 [0.36324311 0.3239782  0.11299388 0.73649879 0.46964199]
 [0.13702776 0.86300609 0.8543407  0.0570825  0.45404893]]

random randint
[[2 4 2 3 3]
 [4 3 3 3 3]
 [4 4 3 3 3]]

full
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]

linspace
[[ 5.          5.45454545  5.90909091  6.36363636]
 [ 6.81818182  7.27272727  7.72727273  8.18181818]
 [ 8.63636364  9.09090909  9.54545455 10.        ]]

arange
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]



In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('H Stack:')
print(np.hstack((a,b)))
print()
print('V Stack:')
print(np.vstack((a,b)))

H Stack:
[1 2 3 4 5 6]

V Stack:
[[1 2 3]
 [4 5 6]]


In [22]:
print(np.transpose(np.vstack((a,b))))

[[1 4]
 [2 5]
 [3 6]]


In [23]:
print((np.vstack((a,b))).reshape(2, 3))
print()
print((np.vstack((a,b))).reshape(3, 2))

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]
